version: "3"
services:
  app:
    container_name: dybvdq-app
    build: ./back/
    volumes:
      - ./:/app
  nginx:
    container_name: dybvdq-nginx
    image: nginx
    volumes:
      - ./front/build:/webroot:ro
      - ./nginx/nginx.conf:/etc/nginx.conf.template:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/htpasswd:/etc/htpasswd:ro
    ports:
      - "80:80"
      - "443:443"
    # Inject environment variables into nginx.conf
    command: /bin/bash -c "envsubst < /etc/nginx.conf.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"

