version: "3"
services:
  app:
    container_name: dybvdq-app
    build: ./back/
    volumes:
      - ./:/app
  nginx:
    container_name: dybvdq-nginx
    image: nginx
    volumes:
      - ./front/build:/webroot:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/htpasswd:/etc/htpasswd:ro
    ports:
      - "80:80"
      - "443:443"
