version: "3"
services:
  app:
    container_name: dybvdq-back
    build: ../back/
    volumes:
      - ../:/app
    environment:
      - DYBVDQ_DB_HOST
      - DYBVDQ_DB_PORT
      - DYBVDQ_DB_USER
      - DYBVDQ_DB_PASS
      - DYBVDQ_DB_NAME
  nginx:
    container_name: dybvdq-nginx
    image: nginx
    volumes:
      - ../front/build:/webroot:ro
      - ../nginx/nginx.conf:/nginx.conf.template:ro
      - ../nginx/start_nginx.sh:/start_nginx.sh:ro
      - ${DYBVDQ_SSL_CERT}:/certs/fullchain.pem:ro
      - ${DYBVDQ_SSL_KEY}:/certs/privkey.pem:ro
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DYBVDQ_HOSTNAME
      - DYBVDQ_AUTH_USER
      - DYBVDQ_AUTH_PASS_HASH
    command: /bin/bash /start_nginx.sh

