version: "3"
services:
  app:
    container_name: dybvdq-app
    build: ../back/
    volumes:
      - ../:/app
  nginx:
    container_name: dybvdq-nginx
    image: nginx
    volumes:
      - ../front/build:/webroot:ro
      - ../nginx/nginx.conf:/nginx.conf.template:ro
      - ../nginx/start_nginx.sh:/start_nginx.sh:ro
      - ${NGINX_SSL_CERT}:/certs/fullchain.pem:ro
      - ${NGINX_SSL_KEY}:/certs/privkey.pem:ro
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOSTNAME
      - NGINX_AUTH_USER
      - NGINX_AUTH_PASS_HASH
    # Inject environment variables into nginx.conf
    command: /bin/bash /start_nginx.sh

