version: "3"
services:
  back:
    container_name: dybvdq-back
    build: ../back/
    volumes:
      - ../back/src:/app
    environment:
      - DYBVDQ_DQ_DB_HOST
      - DYBVDQ_DQ_DB_PORT
      - DYBVDQ_DQ_DB_USER
      - DYBVDQ_DQ_DB_PASS
      - DYBVDQ_DQ_DB_NAME
      - DYBVDQ_APP_DB_PASS
  nginx:
    container_name: dybvdq-nginx
    image: nginx
    volumes:
      - ../front/build:/webroot:ro
      - ../nginx/nginx.conf:/nginx.conf.template:ro
      - ../nginx/start_nginx.sh:/start_nginx.sh:ro
      - ${DYBVDQ_SSL_CERT}:/certs/fullchain.pem:ro
      - ${DYBVDQ_SSL_KEY}:/certs/privkey.pem:ro
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DYBVDQ_HOSTNAME
      - DYBVDQ_AUTH_USER
      - DYBVDQ_AUTH_PASS_HASH
    command: /bin/bash /start_nginx.sh
  app_db:
    container_name: dybvdq-app_db
    image: mariadb
    volumes:
      - ${DYBVDQ_APP_DB_DATA}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DYBVDQ_APP_DB_PASS}
      - MYSQL_DATABASE=app_db
    ports:
      - "3000:3306"
